### PR TITLE
better BlueprintExtensionLibrary

### PR DESCRIPTION
**Pull request by 0x7d8**

### CODE REVIEW

**Comment by prplwtf** [comment]
Could you elaborate on how BaseLibrary is used and limits it's functions per scope (admin, client, console)

**Comment by prplwtf** [comment]
@0x7d8 Have you done everything you wanted to and can this be merged?

**Comment by 0x7d8** [comment]
yes

**Review by prplwtf — APPROVED** [review]
LGTM!

**Pull request merged**
