### PR TITLE
allow passing blueprint file extensions into install

### PR DESCRIPTION
**Pull request by 0x7d8**
allow passing blueprint file names into install because ivy wanted me to make a pr for this

### CODE REVIEW

**Review by prplwtf — COMMENTED** [review]
Code looks good to me. Testing required before merge.

**Comment by 0x7d8** [comment]
ok i test

**Comment by 0x7d8** [comment]
ok done it work

**Comment by 0x7d8** [comment]
u test I am going to 💤💤💤😴😴😴💤💤💤

**Pull request merged**
