### PR TITLE
Bulk extension management, bugfixes and more.

### PR DESCRIPTION
**Pull request by prplwtf**
- Add bash autocomplete which can be enabled by running `source blueprint` in your `.bashrc`.
- Bugfixes regarding `-remove` and other commands.
- Add bulk extension installation/removal support.
- Split up `blueprint.sh` commands into different files which are located under the `scripts/` folder.

... and more

### CODE REVIEW

**Review by itsvic-dev — APPROVED** [review]
LGTM

**Review by Jelcoo — APPROVED** [review]
LGTM

**Review by Ahwxorg — COMMENTED** [review]
LGTM

**Review by Loki-101 — APPROVED** [review]

**Comment by thewander02** [comment]
hiiiiii

**Comment by prplwtf** [comment]
> hiiiiiivy

there is a @thewander02 in my blueprint

**Pull request merged**
